apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo1
  labels:
    app: argocd-demo1

spec:
  replicas: 2

  selector:
    matchLabels:
      app: argocd-demo1

  template:
    metadata:
      labels:
        app: argocd-demo1

    spec:
      containers:
      - name: argocd-demo1
        image: bhadekunal/Argocd-Demo1:4

        imagePullPolicy: Always

        ports:
        - containerPort: 8089

        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"

          limits:
            memory: "1024Mi"
            cpu: "500m"
