apiVersion: v1
kind: Service
metadata:
  name: argocd-demo1

spec:
  type: NodePort

  selector:
    app: argocd-demo1

  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
    nodePort: 30081