apiVersion: v1
kind: Service

metadata:
  name: Argocd-Demo1

spec:
  type: NodePort

  selector:
    app: Argocd-Demo1

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080